import { createContext, useContext, useMemo, useState } from 'react';

const STORAGE_KEY = 'santoregano-language';

export const languages = [
  { code: 'pt', label: 'PT', name: 'Português' },
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'es', label: 'ES', name: 'Español' },
  { code: 'fr', label: 'FR', name: 'Français' },
];

const dictionaries = {
  pt: {
    layout: {
      nav: { home: 'Início', menu: 'Menu', contacts: 'Contactos', order: 'Encomendar' },
      adminArea: 'Área de administrador',
      panel: 'Painel',
      admin: 'Admin',
      cart: 'Carrinho',
      cartAria: 'Carrinho com {count} artigos',
      language: 'Idioma',
      closedLabel: 'Encerrado agora',
      closedNotice: 'Encomendas indisponíveis agora. O menu continua disponível para consulta.',
      footerDesc: 'Pizzas assadas em forno a lenha<br />no coração de Águeda.',
      footerNav: 'Navegação',
      footerContact: 'Contacto',
      copyright: '© 2026 Sant\' Orégano Pizzaria — Águeda, Portugal',
    },
    home: {
      eyebrow: 'Forno a Lenha · Águeda',
      titleTop: 'O Coração<br />de Águeda',
      titleEm: 'Pulsa em<br />Fogo e Ervas.',
      desc: 'No centro histórico da Praça Conde de Águeda, o Sant\' Orégano é onde a tradição italianó-brasileira encontra a alma portuguesa. Pizzas artesanais, assadas em forno a lenha, com ingredientes frescos e paixão genuína.',
      viewMenu: 'Ver Menu →',
      contacts: 'Contactos',
      photoAlt: 'Sant\' Orégano em Águeda',
      visitTag: 'Venha visitar!',
      house: 'A nossa casa',
      ctaTitle: 'Venha provar o melhor de Águeda.',
      ctaDesc: 'Estamos na Praça Conde de Águeda, prontos para o receber com pizzas frescas, ambiente acolhedor e o calor do nosso forno a lenha.',
      directions: 'Como Chegar →',
    },
    menu: {
      eyebrow: 'Galleria dei Sapori',
      title: 'O Nosso Menu',
      desc: 'Cada prato é preparado com ingredientes selecionados e paixão genuína. Escolha, adicione ao carrinho e termine a encomenda sem repetir escolhas.',
      categoriesAria: 'Categorias do menu',
      optionsCount: '{count} opções',
      consultOnly: 'Menu disponível para consulta. Encomendas voltam às 12:00 dentro do horário normal.',
      pastaChoice: 'Escolha a sua massa: Talharim, Penne ou Espaguete.',
      add: 'Adicionar',
      ordersClosed: 'Encomendas fechadas',
      addCart: 'Adicionar ao carrinho',
      addTitle: 'Adicionar ao carrinho',
      unavailableTitle: 'Encomendas indisponíveis neste momento',
      item: 'artigo',
      items: 'artigos',
      viewOrder: 'Ver encomenda',
      added: '{name} adicionado ao carrinho',
      noImage: 'Sem imagem',
      customizePizza: 'Personalize a sua pizza',
      closeCustomization: 'Fechar personalização',
      size: 'Tamanho',
      selectedInMenu: 'Selecionado no menu',
      flavors: 'Sabores',
      flavorsHelp: 'Escolha pizza inteira ou dois sabores',
      wholePizza: 'Pizza inteira',
      halfHalf: 'Meia + meia',
      combine: 'Combine dois sabores',
      secondFlavor: 'Segundo sabor',
      chooseOtherHalf: 'Escolha a outra metade…',
      chooseOption: 'Escolha uma opção…',
      optionForHalf: 'Opção para ½ {name}',
      stuffedCrust: 'Rebordo recheado',
      stuffedCrustHelp: 'Opcional · valor por pizza',
      noCrust: 'Sem rebordo',
      included: 'Incluído',
      totalPizza: 'Total desta pizza',
      closed: 'Fechado',
      customizeProduct: 'Personalize o seu prato',
      productChoiceHelp: 'Selecione uma opção para continuar',
      totalProduct: 'Total deste prato',
      choose: 'Escolher',
      selected: 'Selecionado',
    },
    contacts: {
      ritual: 'O Ritual',
      title: 'Contactos & Horário',
      desc: 'Estamos no coração de Águeda, prontos para o receber. Consulte o nosso horário e venha visitar-nos.',
      schedule: 'Horário',
      monday: 'Segunda-feira',
      days: ['Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', 'Domingo'],
      closed: 'Encerrado',
      note: '* Em feriados, o horário de funcionamento pode ser diferente.',
      where: 'Onde Estamos',
      address: 'Morada',
      phone: 'Telefone',
      directions: '✈ Obter Direções',
      mapTitle: 'Localização Sant\' Orégano',
    },
    closed: {
      title: 'Encomendas fechadas neste momento',
      desc: 'Fora do horário de funcionamento não é possível finalizar encomendas. Pode voltar ao menu e consultar os produtos disponíveis.',
      schedule: 'Horário',
      scheduleValue: 'Terça a Domingo · 12:00 – 23:00',
      monday: 'Segunda-feira',
      closed: 'Encerrado',
      mondayNote: 'Voltamos amanhã às 12:00.',
      normalNote: 'Voltamos a aceitar encomendas durante o horário normal.',
      viewMenu: 'Ver menu',
      adminArea: 'Área de administrador',
    },
    order: {
      eyebrow: 'Ordine dal Forno',
      title: 'A Sua Encomenda',
      desc: 'O que escolheu no menu já está aqui, com o preço calculado. Só falta dizer-nos como quer receber.',
      emptyTitle: 'O carrinho ainda está vazio.',
      emptyDesc: 'Explore o menu e adicione as suas pizzas, entradas, massas, refeições e bebidas.',
      exploreMenu: 'Explorar o menu →',
      yourOrder: 'O seu pedido',
      addMore: '＋ Adicionar mais',
      remove: 'Remover',
      clearCart: 'Esvaziar carrinho',
      contact: 'Contacto',
      name: 'Nome',
      namePlaceholder: 'O seu nome',
      nameError: 'Introduza o seu nome.',
      phone: 'Telefone',
      phoneError: 'Introduza um contacto válido.',
      delivery: 'Entrega',
      takeaway: 'Takeaway',
      takeawayHelp: 'Levanto na pizzaria',
      homeDelivery: 'Entrega em casa',
      fromOne: 'Desde 1€',
      address: 'Morada',
      addressPlaceholder: 'Rua, número, localidade e código postal',
      addressError: 'Introduza a morada de entrega.',
      addressHelp: 'Se a morada não for reconhecida pelo sistema, prossiga mesmo assim. A distância e a taxa serão confirmadas pela pizzaria.',
      routeIdle: 'Escreva a morada completa para calcular a rota.',
      routeLoading: 'A calcular distância por estrada…',
      routeFrom: 'Cerca de {minutes} min desde {place}',
      routeOutside: 'Esta morada fica a {distance} km e está fora da área de entrega de 25 km.',
      routeError: 'Não encontrámos esta morada, mas pode prosseguir com a encomenda. A pizzaria confirmará a distância e a taxa de entrega.',
      outsideError: 'Esta morada está fora da área de entrega de 25 km.',
      mapAttribution: 'Cálculo com dados de',
      when: 'Quando?',
      asap: 'Deixe vazio para receber o mais rápido possível.',
      payment: 'Pagamento',
      cash: 'Dinheiro',
      card: 'Cartão',
      changeFor: 'Preciso troco para',
      changePlaceholder: 'Ex.: 20€',
      changeHelp: 'Deixe vazio se não precisar de troco.',
      kitchenNotes: 'Notas para a cozinha',
      notesPlaceholder: 'Alergias, ponto da massa, instruções de entrega…',
      summary: 'Resumo',
      totalOrder: 'Total da encomenda',
      subtotal: 'Subtotal · {count} artigos',
      deliveryBase: 'Taxa base de entrega',
      deliveryDistance: 'Entrega · {distance} km',
      calculating: 'A calcular…',
      unavailable: 'Indisponível',
      temporary: '{fee} provisório',
      free: 'Grátis',
      currentTotal: 'Total atual',
      feeNote: 'Se a morada não for localizada, pode enviar a encomenda. A pizzaria confirmará a taxa final.',
      sendWhatsApp: 'Enviar via WhatsApp',
      whatsappNote: 'O WhatsApp abre com o pedido e todos os valores já preenchidos.',
      decreaseQty: 'Diminuir quantidade',
      increaseQty: 'Aumentar quantidade',
      noImage: 'Sem imagem',
    },
    categories: {
      traditional: { short: 'Tradicionais' },
      sweet: { short: 'Doces' },
      starters: { short: 'Entradas' },
      pasta: { short: 'Massas' },
      meals: { short: 'Refeições' },
      drinks: { short: 'Bebidas' },
    },
  },
};

dictionaries.en = {
  layout: {
    nav: { home: 'Home', menu: 'Menu', contacts: 'Contact', order: 'Order' },
    adminArea: 'Admin area',
    panel: 'Panel',
    admin: 'Admin',
    cart: 'Cart',
    cartAria: 'Cart with {count} items',
    language: 'Language',
    closedLabel: 'Closed now',
    closedNotice: 'Orders are unavailable right now. The menu is still open to browse.',
    footerDesc: 'Wood-fired pizzas<br />in the heart of Águeda.',
    footerNav: 'Navigation',
    footerContact: 'Contact',
    copyright: '© 2026 Sant\' Orégano Pizzeria — Águeda, Portugal',
  },
  home: {
    eyebrow: 'Wood-fired oven · Águeda',
    titleTop: 'The Heart<br />of Águeda',
    titleEm: 'Beats with<br />Fire and Herbs.',
    desc: 'In the historic centre of Praça Conde de Águeda, Sant\' Orégano is where Italian-Brazilian tradition meets the Portuguese soul. Handmade wood-fired pizzas with fresh ingredients and genuine passion.',
    viewMenu: 'View Menu →',
    contacts: 'Contact',
    photoAlt: 'Sant\' Orégano in Águeda',
    visitTag: 'Come visit!',
    house: 'Our home',
    ctaTitle: 'Come taste the best of Águeda.',
    ctaDesc: 'We are at Praça Conde de Águeda, ready to welcome you with fresh pizzas, a cosy atmosphere and the warmth of our wood-fired oven.',
    directions: 'Get Directions →',
  },
  menu: {
    eyebrow: 'Gallery of Flavours',
    title: 'Our Menu',
    desc: 'Every dish is prepared with selected ingredients and genuine passion. Choose, add to cart, and finish your order without repeating choices.',
    categoriesAria: 'Menu categories',
    optionsCount: '{count} options',
    consultOnly: 'Menu available for browsing. Orders return at 12:00 during normal opening hours.',
    pastaChoice: 'Choose your pasta: tagliatelle, penne or spaghetti.',
    add: 'Add',
    ordersClosed: 'Orders closed',
    addCart: 'Add to cart',
    addTitle: 'Add to cart',
    unavailableTitle: 'Orders unavailable right now',
    item: 'item',
    items: 'items',
    viewOrder: 'View order',
    added: '{name} added to cart',
    noImage: 'No image',
    customizePizza: 'Customize your pizza',
    closeCustomization: 'Close customization',
    size: 'Size',
    selectedInMenu: 'Selected in the menu',
    flavors: 'Flavours',
    flavorsHelp: 'Choose a whole pizza or two flavours',
    wholePizza: 'Whole pizza',
    halfHalf: 'Half + half',
    combine: 'Combine two flavours',
    secondFlavor: 'Second flavour',
    chooseOtherHalf: 'Choose the other half…',
    chooseOption: 'Choose an option…',
    optionForHalf: 'Option for ½ {name}',
    stuffedCrust: 'Stuffed crust',
    stuffedCrustHelp: 'Optional · price per pizza',
    noCrust: 'No stuffed crust',
    included: 'Included',
    totalPizza: 'Total for this pizza',
    closed: 'Closed',
    customizeProduct: 'Customize your dish',
    productChoiceHelp: 'Select an option to continue',
    totalProduct: 'Total for this dish',
    choose: 'Choose',
    selected: 'Selected',
  },
  contacts: {
    ritual: 'The Ritual',
    title: 'Contact & Hours',
    desc: 'We are in the heart of Águeda, ready to welcome you. Check our opening hours and come visit us.',
    schedule: 'Opening hours',
    monday: 'Monday',
    days: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    closed: 'Closed',
    note: '* Opening hours may differ on holidays.',
    where: 'Where We Are',
    address: 'Address',
    phone: 'Phone',
    directions: '✈ Get Directions',
    mapTitle: 'Sant\' Orégano location',
  },
  closed: {
    title: 'Orders are closed right now',
    desc: 'Outside opening hours it is not possible to complete orders. You can return to the menu and browse the available products.',
    schedule: 'Hours',
    scheduleValue: 'Tuesday to Sunday · 12:00 – 23:00',
    monday: 'Monday',
    closed: 'Closed',
    mondayNote: 'We return tomorrow at 12:00.',
    normalNote: 'We will accept orders again during normal opening hours.',
    viewMenu: 'View menu',
    adminArea: 'Admin area',
  },
  order: {
    eyebrow: 'Order from the Oven',
    title: 'Your Order',
    desc: 'Everything you chose from the menu is already here with the price calculated. Just tell us how you want to receive it.',
    emptyTitle: 'Your cart is still empty.',
    emptyDesc: 'Explore the menu and add your pizzas, starters, pasta, meals and drinks.',
    exploreMenu: 'Explore menu →',
    yourOrder: 'Your order',
    addMore: '＋ Add more',
    remove: 'Remove',
    clearCart: 'Empty cart',
    contact: 'Contact',
    name: 'Name',
    namePlaceholder: 'Your name',
    nameError: 'Enter your name.',
    phone: 'Phone',
    phoneError: 'Enter a valid contact number.',
    delivery: 'Delivery',
    takeaway: 'Takeaway',
    takeawayHelp: 'I will pick up at the pizzeria',
    homeDelivery: 'Home delivery',
    fromOne: 'From €1',
    address: 'Address',
    addressPlaceholder: 'Street, number, town and postcode',
    addressError: 'Enter the delivery address.',
    addressHelp: 'If the system does not recognize the address, continue anyway. Distance and fee will be confirmed by the pizzeria.',
    routeIdle: 'Write the full address to calculate the route.',
    routeLoading: 'Calculating road distance…',
    routeFrom: 'Around {minutes} min from {place}',
    routeOutside: 'This address is {distance} km away and outside the 25 km delivery area.',
    routeError: 'We could not find this address, but you can continue with the order. The pizzeria will confirm the distance and delivery fee.',
    outsideError: 'This address is outside the 25 km delivery area.',
    mapAttribution: 'Calculation with data from',
    when: 'When?',
    asap: 'Leave empty to receive it as soon as possible.',
    payment: 'Payment',
    cash: 'Cash',
    card: 'Card',
    changeFor: 'I need change for',
    changePlaceholder: 'E.g. €20',
    changeHelp: 'Leave empty if you do not need change.',
    kitchenNotes: 'Notes for the kitchen',
    notesPlaceholder: 'Allergies, dough preference, delivery instructions…',
    summary: 'Summary',
    totalOrder: 'Order total',
    subtotal: 'Subtotal · {count} items',
    deliveryBase: 'Base delivery fee',
    deliveryDistance: 'Delivery · {distance} km',
    calculating: 'Calculating…',
    unavailable: 'Unavailable',
    temporary: '{fee} temporary',
    free: 'Free',
    currentTotal: 'Current total',
    feeNote: 'If the address is not located, you can send the order. The pizzeria will confirm the final fee.',
    sendWhatsApp: 'Send via WhatsApp',
    whatsappNote: 'WhatsApp opens with the order and all values already filled in.',
    decreaseQty: 'Decrease quantity',
    increaseQty: 'Increase quantity',
    noImage: 'No image',
  },
  categories: {
    traditional: { short: 'Traditional' },
    sweet: { short: 'Sweet' },
    starters: { short: 'Starters' },
    pasta: { short: 'Pasta' },
    meals: { short: 'Meals' },
    drinks: { short: 'Drinks' },
  },
};

dictionaries.es = {
  ...dictionaries.en,
  layout: {
    ...dictionaries.en.layout,
    nav: { home: 'Inicio', menu: 'Menú', contacts: 'Contacto', order: 'Pedir' },
    adminArea: 'Área de administrador',
    cart: 'Carrito',
    cartAria: 'Carrito con {count} artículos',
    language: 'Idioma',
    closedLabel: 'Cerrado ahora',
    closedNotice: 'Pedidos no disponibles ahora. El menú sigue disponible para consultar.',
    footerDesc: 'Pizzas al horno de leña<br />en el corazón de Águeda.',
    footerNav: 'Navegación',
    footerContact: 'Contacto',
    copyright: '© 2026 Sant\' Orégano Pizzería — Águeda, Portugal',
  },
  home: {
    eyebrow: 'Horno de leña · Águeda',
    titleTop: 'El Corazón<br />de Águeda',
    titleEm: 'Late con<br />Fuego y Hierbas.',
    desc: 'En el centro histórico de Praça Conde de Águeda, Sant\' Orégano es donde la tradición italo-brasileña se encuentra con el alma portuguesa. Pizzas artesanales al horno de leña, con ingredientes frescos y pasión auténtica.',
    viewMenu: 'Ver Menú →',
    contacts: 'Contacto',
    photoAlt: 'Sant\' Orégano en Águeda',
    visitTag: '¡Ven a visitarnos!',
    house: 'Nuestra casa',
    ctaTitle: 'Ven a probar lo mejor de Águeda.',
    ctaDesc: 'Estamos en Praça Conde de Águeda, listos para recibirte con pizzas frescas, un ambiente acogedor y el calor de nuestro horno de leña.',
    directions: 'Cómo Llegar →',
  },
  menu: {
    ...dictionaries.en.menu,
    eyebrow: 'Galería de Sabores',
    title: 'Nuestro Menú',
    desc: 'Cada plato se prepara con ingredientes seleccionados y pasión auténtica. Elige, añade al carrito y termina tu pedido sin repetir elecciones.',
    categoriesAria: 'Categorías del menú',
    optionsCount: '{count} opciones',
    consultOnly: 'Menú disponible para consulta. Los pedidos vuelven a las 12:00 dentro del horario normal.',
    pastaChoice: 'Elige tu pasta: tallarines, penne o espaguetis.',
    add: 'Añadir',
    ordersClosed: 'Pedidos cerrados',
    addCart: 'Añadir al carrito',
    addTitle: 'Añadir al carrito',
    unavailableTitle: 'Pedidos no disponibles ahora',
    item: 'artículo',
    items: 'artículos',
    viewOrder: 'Ver pedido',
    added: '{name} añadido al carrito',
    noImage: 'Sin imagen',
    customizePizza: 'Personaliza tu pizza',
    closeCustomization: 'Cerrar personalización',
    size: 'Tamaño',
    selectedInMenu: 'Seleccionado en el menú',
    flavors: 'Sabores',
    flavorsHelp: 'Elige pizza entera o dos sabores',
    wholePizza: 'Pizza entera',
    halfHalf: 'Mitad + mitad',
    combine: 'Combina dos sabores',
    secondFlavor: 'Segundo sabor',
    chooseOtherHalf: 'Elige la otra mitad…',
    chooseOption: 'Elige una opción…',
    optionForHalf: 'Opción para ½ {name}',
    stuffedCrust: 'Borde relleno',
    stuffedCrustHelp: 'Opcional · precio por pizza',
    noCrust: 'Sin borde relleno',
    included: 'Incluido',
    totalPizza: 'Total de esta pizza',
    closed: 'Cerrado',
    customizeProduct: 'Personaliza tu plato',
    productChoiceHelp: 'Selecciona una opción para continuar',
    totalProduct: 'Total de este plato',
    choose: 'Elegir',
    selected: 'Seleccionado',
  },
  contacts: {
    ritual: 'El Ritual',
    title: 'Contacto y Horario',
    desc: 'Estamos en el corazón de Águeda, listos para recibirte. Consulta nuestro horario y ven a visitarnos.',
    schedule: 'Horario',
    monday: 'Lunes',
    days: ['Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    closed: 'Cerrado',
    note: '* En festivos, el horario puede ser diferente.',
    where: 'Dónde Estamos',
    address: 'Dirección',
    phone: 'Teléfono',
    directions: '✈ Cómo Llegar',
    mapTitle: 'Ubicación de Sant\' Orégano',
  },
  closed: {
    title: 'Pedidos cerrados ahora',
    desc: 'Fuera del horario de apertura no es posible finalizar pedidos. Puedes volver al menú y consultar los productos disponibles.',
    schedule: 'Horario',
    scheduleValue: 'Martes a domingo · 12:00 – 23:00',
    monday: 'Lunes',
    closed: 'Cerrado',
    mondayNote: 'Volvemos mañana a las 12:00.',
    normalNote: 'Volveremos a aceptar pedidos durante el horario normal.',
    viewMenu: 'Ver menú',
    adminArea: 'Área de administrador',
  },
  order: {
    ...dictionaries.en.order,
    eyebrow: 'Pedido del Horno',
    title: 'Tu Pedido',
    desc: 'Lo que elegiste del menú ya está aquí, con el precio calculado. Solo falta decirnos cómo quieres recibirlo.',
    emptyTitle: 'Tu carrito aún está vacío.',
    emptyDesc: 'Explora el menú y añade tus pizzas, entrantes, pastas, platos y bebidas.',
    exploreMenu: 'Explorar menú →',
    yourOrder: 'Tu pedido',
    addMore: '＋ Añadir más',
    remove: 'Eliminar',
    clearCart: 'Vaciar carrito',
    contact: 'Contacto',
    name: 'Nombre',
    namePlaceholder: 'Tu nombre',
    nameError: 'Introduce tu nombre.',
    phone: 'Teléfono',
    phoneError: 'Introduce un contacto válido.',
    delivery: 'Entrega',
    takeaway: 'Takeaway',
    takeawayHelp: 'Recojo en la pizzería',
    homeDelivery: 'Entrega a domicilio',
    fromOne: 'Desde 1€',
    address: 'Dirección',
    addressPlaceholder: 'Calle, número, localidad y código postal',
    addressError: 'Introduce la dirección de entrega.',
    addressHelp: 'Si el sistema no reconoce la dirección, continúa igualmente. La distancia y la tasa serán confirmadas por la pizzería.',
    routeIdle: 'Escribe la dirección completa para calcular la ruta.',
    routeLoading: 'Calculando distancia por carretera…',
    routeFrom: 'Aprox. {minutes} min desde {place}',
    routeOutside: 'Esta dirección está a {distance} km y fuera del área de entrega de 25 km.',
    routeError: 'No encontramos esta dirección, pero puedes continuar con el pedido. La pizzería confirmará la distancia y la tasa.',
    outsideError: 'Esta dirección está fuera del área de entrega de 25 km.',
    mapAttribution: 'Cálculo con datos de',
    when: '¿Cuándo?',
    asap: 'Déjalo vacío para recibirlo lo antes posible.',
    payment: 'Pago',
    cash: 'Efectivo',
    card: 'Tarjeta',
    changeFor: 'Necesito cambio para',
    changePlaceholder: 'Ej.: 20€',
    changeHelp: 'Déjalo vacío si no necesitas cambio.',
    kitchenNotes: 'Notas para la cocina',
    notesPlaceholder: 'Alergias, punto de la masa, instrucciones de entrega…',
    summary: 'Resumen',
    totalOrder: 'Total del pedido',
    subtotal: 'Subtotal · {count} artículos',
    deliveryBase: 'Tasa base de entrega',
    deliveryDistance: 'Entrega · {distance} km',
    calculating: 'Calculando…',
    unavailable: 'No disponible',
    temporary: '{fee} provisional',
    free: 'Gratis',
    currentTotal: 'Total actual',
    feeNote: 'Si no se localiza la dirección, puedes enviar el pedido. La pizzería confirmará la tasa final.',
    sendWhatsApp: 'Enviar por WhatsApp',
    whatsappNote: 'WhatsApp se abre con el pedido y todos los valores ya rellenados.',
    decreaseQty: 'Disminuir cantidad',
    increaseQty: 'Aumentar cantidad',
    noImage: 'Sin imagen',
  },
  categories: {
    traditional: { short: 'Tradicionales' },
    sweet: { short: 'Dulces' },
    starters: { short: 'Entrantes' },
    pasta: { short: 'Pastas' },
    meals: { short: 'Platos' },
    drinks: { short: 'Bebidas' },
  },
};

dictionaries.fr = {
  ...dictionaries.en,
  layout: {
    ...dictionaries.en.layout,
    nav: { home: 'Accueil', menu: 'Menu', contacts: 'Contact', order: 'Commander' },
    adminArea: 'Espace admin',
    panel: 'Panneau',
    cart: 'Panier',
    cartAria: 'Panier avec {count} articles',
    language: 'Langue',
    closedLabel: 'Fermé',
    closedNotice: 'Commandes indisponibles maintenant. Le menu reste consultable.',
    footerDesc: 'Pizzas cuites au feu de bois<br />au cœur d’Águeda.',
    footerNav: 'Navigation',
    footerContact: 'Contact',
    copyright: '© 2026 Sant\' Orégano Pizzeria — Águeda, Portugal',
  },
  home: {
    eyebrow: 'Four à bois · Águeda',
    titleTop: 'Le Cœur<br />d’Águeda',
    titleEm: 'Bat au rythme<br />du Feu et des Herbes.',
    desc: 'Dans le centre historique de Praça Conde de Águeda, Sant\' Orégano réunit la tradition italo-brésilienne et l’âme portugaise. Des pizzas artisanales cuites au feu de bois, avec des ingrédients frais et une vraie passion.',
    viewMenu: 'Voir le Menu →',
    contacts: 'Contact',
    photoAlt: 'Sant\' Orégano à Águeda',
    visitTag: 'Venez nous voir !',
    house: 'Notre maison',
    ctaTitle: 'Venez goûter le meilleur d’Águeda.',
    ctaDesc: 'Nous sommes à Praça Conde de Águeda, prêts à vous accueillir avec des pizzas fraîches, une ambiance chaleureuse et la chaleur de notre four à bois.',
    directions: 'Itinéraire →',
  },
  menu: {
    ...dictionaries.en.menu,
    eyebrow: 'Galerie des Saveurs',
    title: 'Notre Menu',
    desc: 'Chaque plat est préparé avec des ingrédients sélectionnés et une vraie passion. Choisissez, ajoutez au panier et terminez votre commande sans répéter vos choix.',
    categoriesAria: 'Catégories du menu',
    optionsCount: '{count} options',
    consultOnly: 'Menu disponible en consultation. Les commandes reprennent à 12:00 pendant les horaires normaux.',
    pastaChoice: 'Choisissez vos pâtes : tagliatelles, penne ou spaghetti.',
    add: 'Ajouter',
    ordersClosed: 'Commandes fermées',
    addCart: 'Ajouter au panier',
    addTitle: 'Ajouter au panier',
    unavailableTitle: 'Commandes indisponibles maintenant',
    item: 'article',
    items: 'articles',
    viewOrder: 'Voir la commande',
    added: '{name} ajouté au panier',
    noImage: 'Sans image',
    customizePizza: 'Personnalisez votre pizza',
    closeCustomization: 'Fermer la personnalisation',
    size: 'Taille',
    selectedInMenu: 'Sélectionné dans le menu',
    flavors: 'Saveurs',
    flavorsHelp: 'Choisissez une pizza entière ou deux saveurs',
    wholePizza: 'Pizza entière',
    halfHalf: 'Moitié + moitié',
    combine: 'Combinez deux saveurs',
    secondFlavor: 'Deuxième saveur',
    chooseOtherHalf: 'Choisissez l’autre moitié…',
    chooseOption: 'Choisissez une option…',
    optionForHalf: 'Option pour ½ {name}',
    stuffedCrust: 'Croûte farcie',
    stuffedCrustHelp: 'Optionnel · prix par pizza',
    noCrust: 'Sans croûte farcie',
    included: 'Inclus',
    totalPizza: 'Total de cette pizza',
    closed: 'Fermé',
    customizeProduct: 'Personnalisez votre plat',
    productChoiceHelp: 'Sélectionnez une option pour continuer',
    totalProduct: 'Total de ce plat',
    choose: 'Choisir',
    selected: 'Sélectionné',
  },
  contacts: {
    ritual: 'Le Rituel',
    title: 'Contact & Horaires',
    desc: 'Nous sommes au cœur d’Águeda, prêts à vous accueillir. Consultez nos horaires et venez nous voir.',
    schedule: 'Horaires',
    monday: 'Lundi',
    days: ['Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
    closed: 'Fermé',
    note: '* Les horaires peuvent varier les jours fériés.',
    where: 'Où Nous Trouver',
    address: 'Adresse',
    phone: 'Téléphone',
    directions: '✈ Itinéraire',
    mapTitle: 'Localisation Sant\' Orégano',
  },
  closed: {
    title: 'Commandes fermées maintenant',
    desc: 'En dehors des horaires d’ouverture, il n’est pas possible de finaliser une commande. Vous pouvez retourner au menu et consulter les produits disponibles.',
    schedule: 'Horaires',
    scheduleValue: 'Mardi à dimanche · 12:00 – 23:00',
    monday: 'Lundi',
    closed: 'Fermé',
    mondayNote: 'Nous revenons demain à 12:00.',
    normalNote: 'Nous accepterons à nouveau les commandes pendant les horaires normaux.',
    viewMenu: 'Voir le menu',
    adminArea: 'Espace admin',
  },
  order: {
    ...dictionaries.en.order,
    eyebrow: 'Commande du Four',
    title: 'Votre Commande',
    desc: 'Ce que vous avez choisi dans le menu est déjà ici, avec le prix calculé. Dites-nous simplement comment vous souhaitez le recevoir.',
    emptyTitle: 'Votre panier est encore vide.',
    emptyDesc: 'Explorez le menu et ajoutez vos pizzas, entrées, pâtes, plats et boissons.',
    exploreMenu: 'Explorer le menu →',
    yourOrder: 'Votre commande',
    addMore: '＋ Ajouter plus',
    remove: 'Retirer',
    clearCart: 'Vider le panier',
    contact: 'Contact',
    name: 'Nom',
    namePlaceholder: 'Votre nom',
    nameError: 'Indiquez votre nom.',
    phone: 'Téléphone',
    phoneError: 'Indiquez un contact valide.',
    delivery: 'Livraison',
    takeaway: 'À emporter',
    takeawayHelp: 'Je récupère à la pizzeria',
    homeDelivery: 'Livraison à domicile',
    fromOne: 'À partir de 1€',
    address: 'Adresse',
    addressPlaceholder: 'Rue, numéro, ville et code postal',
    addressError: 'Indiquez l’adresse de livraison.',
    addressHelp: 'Si le système ne reconnaît pas l’adresse, continuez quand même. La distance et les frais seront confirmés par la pizzeria.',
    routeIdle: 'Écrivez l’adresse complète pour calculer l’itinéraire.',
    routeLoading: 'Calcul de la distance par route…',
    routeFrom: 'Environ {minutes} min depuis {place}',
    routeOutside: 'Cette adresse est à {distance} km et hors de la zone de livraison de 25 km.',
    routeError: 'Nous n’avons pas trouvé cette adresse, mais vous pouvez continuer la commande. La pizzeria confirmera la distance et les frais.',
    outsideError: 'Cette adresse est hors de la zone de livraison de 25 km.',
    mapAttribution: 'Calcul avec les données de',
    when: 'Quand ?',
    asap: 'Laissez vide pour recevoir le plus rapidement possible.',
    payment: 'Paiement',
    cash: 'Espèces',
    card: 'Carte',
    changeFor: 'J’ai besoin de monnaie pour',
    changePlaceholder: 'Ex. : 20€',
    changeHelp: 'Laissez vide si vous n’avez pas besoin de monnaie.',
    kitchenNotes: 'Notes pour la cuisine',
    notesPlaceholder: 'Allergies, cuisson de la pâte, instructions de livraison…',
    summary: 'Résumé',
    totalOrder: 'Total de la commande',
    subtotal: 'Sous-total · {count} articles',
    deliveryBase: 'Frais de livraison de base',
    deliveryDistance: 'Livraison · {distance} km',
    calculating: 'Calcul…',
    unavailable: 'Indisponible',
    temporary: '{fee} provisoire',
    free: 'Gratuit',
    currentTotal: 'Total actuel',
    feeNote: 'Si l’adresse n’est pas localisée, vous pouvez envoyer la commande. La pizzeria confirmera les frais finaux.',
    sendWhatsApp: 'Envoyer via WhatsApp',
    whatsappNote: 'WhatsApp s’ouvre avec la commande et toutes les valeurs déjà remplies.',
    decreaseQty: 'Diminuer la quantité',
    increaseQty: 'Augmenter la quantité',
    noImage: 'Sans image',
  },
  categories: {
    traditional: { short: 'Traditionnelles' },
    sweet: { short: 'Sucrées' },
    starters: { short: 'Entrées' },
    pasta: { short: 'Pâtes' },
    meals: { short: 'Plats' },
    drinks: { short: 'Boissons' },
  },
};

const LanguageContext = createContext(null);

function readLanguage() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    return languages.some((item) => item.code === stored) ? stored : 'pt';
  } catch {
    return 'pt';
  }
}

function getPathValue(source, path) {
  return path.split('.').reduce((value, key) => value?.[key], source);
}

function interpolate(value, replacements = {}) {
  if (typeof value !== 'string') return value;
  return value.replace(/\{(\w+)\}/g, (_, key) => replacements[key] ?? '');
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(readLanguage);

  const setLanguage = (nextLanguage) => {
    const safeLanguage = languages.some((item) => item.code === nextLanguage) ? nextLanguage : 'pt';
    setLanguageState(safeLanguage);
    try {
      localStorage.setItem(STORAGE_KEY, safeLanguage);
    } catch {
      // Language choice is a convenience; blocked storage should not break the site.
    }
  };

  const value = useMemo(() => {
    const dictionary = dictionaries[language] || dictionaries.pt;
    const t = (key, replacements = {}, fallback = '') => {
      const translated = getPathValue(dictionary, key) ?? getPathValue(dictionaries.pt, key) ?? fallback;
      return interpolate(translated, replacements);
    };

    return { language, languages, setLanguage, t };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
